<a href="https://colab.research.google.com/github/taibaakhtar/Clinical-dataVerse-Analysis/blob/main/cancer_patient_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
#from imblearn.over_sampling import RandomOverSampler
import gspread

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)
worksheet = gc.open('cancer patient data sets').worksheet('Sheet')
data = worksheet.get_all_values()

import pandas as pd
df = pd.DataFrame(data[1:], columns=data[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   object
 2   Gender                    1000 non-null   object
 3   Air Pollution             1000 non-null   object
 4   Alcohol use               1000 non-null   object
 5   Dust Allergy              1000 non-null   object
 6   OccuPational Hazards      1000 non-null   object
 7   Genetic Risk              1000 non-null   object
 8   chronic Lung Disease      1000 non-null   object
 9   Balanced Diet             1000 non-null   object
 10  Obesity                   1000 non-null   object
 11  Smoking                   1000 non-null   object
 12  Passive Smoker            1000 non-null   object
 13  Chest Pain                1000 non-null   object
 14  Coughing of Blood        

In [ ]:
df['Level'] = df['Level'].map({'Low': 1, 'Medium': 2, 'High': 3})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Patient Id                1000 non-null   object
 1   Age                       1000 non-null   object
 2   Gender                    1000 non-null   object
 3   Air Pollution             1000 non-null   object
 4   Alcohol use               1000 non-null   object
 5   Dust Allergy              1000 non-null   object
 6   OccuPational Hazards      1000 non-null   object
 7   Genetic Risk              1000 non-null   object
 8   chronic Lung Disease      1000 non-null   object
 9   Balanced Diet             1000 non-null   object
 10  Obesity                   1000 non-null   object
 11  Smoking                   1000 non-null   object
 12  Passive Smoker            1000 non-null   object
 13  Chest Pain                1000 non-null   object
 14  Coughing of Blood        

In [ ]:
df = df.drop(columns=['Patient Id'])
df.head()

Age Gender Air Pollution Alcohol use Dust Allergy OccuPational Hazards  \
0  33      1             2           4            5                    4   
1  17      1             3           1            5                    3   
2  35      1             4           5            6                    5   
3  37      1             7           7            7                    7   
4  46      1             6           8            7                    7   

  Genetic Risk chronic Lung Disease Balanced Diet Obesity  ... Fatigue  \
0            3                    2             2       4  ...       3   
1            4                    2             2       2  ...       1   
2            5                    4             6       7  ...       8   
3            6                    7             7       7  ...       4   
4            7                    6             7       7  ...       3   

  Weight Loss Shortness of Breath Wheezing Swallowing Difficulty  \
0           4                   2        2                     3   
1           3                   7        8                     6   
2           7                   9        2                     1   
3           2                   3        1                     4   
4           2                   4        1                     4   

  Clubbing of Finger Nails Frequent Cold Dry Cough Snoring Level  
0                        1             2         3       4     1  
1                        2             1         7       2     2  
2                        4             6         7       2     3  
3                        5             6         7       5     3  
4                        2             4         2       3     3  

[5 rows x 24 columns]

In [ ]:
dfs = df.drop(columns=['Level'])
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1000 non-null   object
 1   Gender                    1000 non-null   object
 2   Air Pollution             1000 non-null   object
 3   Alcohol use               1000 non-null   object
 4   Dust Allergy              1000 non-null   object
 5   OccuPational Hazards      1000 non-null   object
 6   Genetic Risk              1000 non-null   object
 7   chronic Lung Disease      1000 non-null   object
 8   Balanced Diet             1000 non-null   object
 9   Obesity                   1000 non-null   object
 10  Smoking                   1000 non-null   object
 11  Passive Smoker            1000 non-null   object
 12  Chest Pain                1000 non-null   object
 13  Coughing of Blood         1000 non-null   object
 14  Fatigue                  

In [ ]:
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1000 non-null   int64
 1   Gender                    1000 non-null   int64
 2   Air Pollution             1000 non-null   int64
 3   Alcohol use               1000 non-null   int64
 4   Dust Allergy              1000 non-null   int64
 5   OccuPational Hazards      1000 non-null   int64
 6   Genetic Risk              1000 non-null   int64
 7   chronic Lung Disease      1000 non-null   int64
 8   Balanced Diet             1000 non-null   int64
 9   Obesity                   1000 non-null   int64
 10  Smoking                   1000 non-null   int64
 11  Passive Smoker            1000 non-null   int64
 12  Chest Pain                1000 non-null   int64
 13  Coughing of Blood         1000 non-null   int64
 14  Fatigue                   1000 non-null  

In [ ]:
df.describe().T

count    mean        std   min    25%   50%   75%  \
Age                       1000.0  37.174  12.005493  14.0  27.75  36.0  45.0   
Gender                    1000.0   1.402   0.490547   1.0   1.00   1.0   2.0   
Air Pollution             1000.0   3.840   2.030400   1.0   2.00   3.0   6.0   
Alcohol use               1000.0   4.563   2.620477   1.0   2.00   5.0   7.0   
Dust Allergy              1000.0   5.165   1.980833   1.0   4.00   6.0   7.0   
OccuPational Hazards      1000.0   4.840   2.107805   1.0   3.00   5.0   7.0   
Genetic Risk              1000.0   4.580   2.126999   1.0   2.00   5.0   7.0   
chronic Lung Disease      1000.0   4.380   1.848518   1.0   3.00   4.0   6.0   
Balanced Diet             1000.0   4.491   2.135528   1.0   2.00   4.0   7.0   
Obesity                   1000.0   4.465   2.124921   1.0   3.00   4.0   7.0   
Smoking                   1000.0   3.948   2.495902   1.0   2.00   3.0   7.0   
Passive Smoker            1000.0   4.195   2.311778   1.0   2.00   4.0   7.0   
Chest Pain                1000.0   4.438   2.280209   1.0   2.00   4.0   7.0   
Coughing of Blood         1000.0   4.859   2.427965   1.0   3.00   4.0   7.0   
Fatigue                   1000.0   3.856   2.244616   1.0   2.00   3.0   5.0   
Weight Loss               1000.0   3.855   2.206546   1.0   2.00   3.0   6.0   
Shortness of Breath       1000.0   4.240   2.285087   1.0   2.00   4.0   6.0   
Wheezing                  1000.0   3.777   2.041921   1.0   2.00   4.0   5.0   
Swallowing Difficulty     1000.0   3.746   2.270383   1.0   2.00   4.0   5.0   
Clubbing of Finger Nails  1000.0   3.923   2.388048   1.0   2.00   4.0   5.0   
Frequent Cold             1000.0   3.536   1.832502   1.0   2.00   3.0   5.0   
Dry Cough                 1000.0   3.853   2.039007   1.0   2.00   4.0   6.0   
Snoring                   1000.0   2.926   1.474686   1.0   2.00   3.0   4.0   
Level                     1000.0   2.062   0.815365   1.0   1.00   2.0   3.0   

                           max  
Age                       73.0  
Gender                     2.0  
Air Pollution              8.0  
Alcohol use                8.0  
Dust Allergy               8.0  
OccuPational Hazards       8.0  
Genetic Risk               7.0  
chronic Lung Disease       7.0  
Balanced Diet              7.0  
Obesity                    7.0  
Smoking                    8.0  
Passive Smoker             8.0  
Chest Pain                 9.0  
Coughing of Blood          9.0  
Fatigue                    9.0  
Weight Loss                8.0  
Shortness of Breath        9.0  
Wheezing                   8.0  
Swallowing Difficulty      8.0  
Clubbing of Finger Nails   9.0  
Frequent Cold              7.0  
Dry Cough                  7.0  
Snoring                    7.0  
Level                      3.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1000 non-null   int64
 1   Gender                    1000 non-null   int64
 2   Air Pollution             1000 non-null   int64
 3   Alcohol use               1000 non-null   int64
 4   Dust Allergy              1000 non-null   int64
 5   OccuPational Hazards      1000 non-null   int64
 6   Genetic Risk              1000 non-null   int64
 7   chronic Lung Disease      1000 non-null   int64
 8   Balanced Diet             1000 non-null   int64
 9   Obesity                   1000 non-null   int64
 10  Smoking                   1000 non-null   int64
 11  Passive Smoker            1000 non-null   int64
 12  Chest Pain                1000 non-null   int64
 13  Coughing of Blood         1000 non-null   int64
 14  Fatigue                   1000 non-null  

# Train, Validate and Test

In [ ]:
# Splitting the dataset into 60, 20, 20
train, valid, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

In [ ]:
def scale_dataset(dataframe):
  X = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  X = scaler.fit_transform(X)

  # if oversample:
  #   ros = RandomOverSampler()
  #   X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape(y, (-1, 1))))

  return data, X, y

train, X_train, y_train = scale_dataset(train)
valid, X_valid, y_valid = scale_dataset(valid)
test, X_test, y_test = scale_dataset(test)


# kNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn = KNeighborsClassifier(n_neighbors=5)  # Adjust 'n_neighbors' as needed

knn.fit(X_train, y_train)

y_pred_valid_knn = knn.predict(X_valid)

# Evaluate this model
print("KNN Validation Accuracy:", accuracy_score(y_valid, y_pred_valid_knn))
print("KNN Validation Classification Report:")
print(classification_report(y_valid, y_pred_valid_knn))
print("Confusion matrix: ")
print(confusion_matrix(y_valid, y_pred_valid_knn))

KNN Validation Accuracy: 1.0
KNN Validation Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        55
           2       1.00      1.00      1.00        59
           3       1.00      1.00      1.00        86

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

Confusion matrix: 
[[55  0  0]
 [ 0 59  0]
 [ 0  0 86]]


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Assuming X_train and y_train are your features and training target
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

knn = KNeighborsClassifier(n_neighbors=5)
cv_scores = cross_val_score(knn, X_train_scaled, y_train, cv=10, scoring='accuracy')

print("Cross-Validation Accuracy (Training Set):", cv_scores.mean())

# Using validation set explicitly for final evaluation after tuning
X_valid_scaled = scaler.transform(X_valid)
knn.fit(X_train_scaled, y_train)
validation_accuracy = knn.score(X_valid_scaled, y_valid)
print("Validation Set Accuracy:", validation_accuracy)


Cross-Validation Accuracy (Training Set): 1.0
Validation Set Accuracy: 1.0


# Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize Random Forest
rf = RandomForestClassifier(random_state=42)

# Fit the model
rf.fit(X_train, y_train)

# Validate
y_pred_valid_rf = rf.predict(X_valid)

# Evaluate
print("Random Forest Validation Accuracy:", accuracy_score(y_valid, y_pred_valid_rf))
print("Random Forest Validation Classification Report:")
print(classification_report(y_valid, y_pred_valid_rf))

Random Forest Validation Accuracy: 1.0
Random Forest Validation Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        55
           2       1.00      1.00      1.00        59
           3       1.00      1.00      1.00        86

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200



In [ ]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

grid_search_rf = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search_rf.fit(X_train, y_train)

print("Best Parameters for Random Forest:", grid_search_rf.best_params_)

Best Parameters for Random Forest: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 50}
